function DM_prepClient(csid,client){client.DM_addEncToLoc(asNodeName,asNodeValue);
client.DM_addEncToLoc("Author",asAuthor);
}function audSciWrite(){asNodeName=typeof thisNode!="undefined"&&thisNode!=""?"thisNode":"commercialNode";
asNodeValue=typeof thisNode!="undefined"&&thisNode!=""?thisNode:commercialNode;
asNodeValue=asNodeValue.toLowerCase().replace(/\/$/gi,"");
asAuthor="";
if(typeof wp_meta_data.author!=="undefined"){var i=wp_meta_data.author.length;
while(i--){asAuthor+=wp_meta_data.author[i]+(i!==0?",":"");
}}else{asAuthor="undefined";
}if(location.href.match("test_rs_values")){document.write(asNodeName+"="+asNodeValue+"<br/>");
document.write("Author="+asAuthor+"<br/>");
}if(asNodeName=="thisNode"&&typeof getCookie!="undefined"&&getCookie("WPATC")){var reg_values=getCookie("WPATC").split(":");
for(i=0;
reg_values[i];
i++){var rv_in_use=reg_values[i].split("=");
DM_addEncToLoc(rv_in_use[0],rv_in_use[1]);
if(location.href.match("test_rs_values")){document.write(rv_in_use[0]+"="+rv_in_use[1]+"<br/>");
}}}DM_tag();
}try{audSciWrite();
}catch(e){}if(typeof QUANTCAST_ON=="undefined"||QUANTCAST_ON){_qoptions={qacct:"p-5cYn7dCzvaeyA"};
try{function h(x){return(encodeURIComponent||escape)(x||"");
}var qo="",qm="",m="webpage",e="load",u="undefined";
if(typeof _qoptions!=u&&_qoptions){var q=_qoptions;
for(var k in q){if(typeof (q[k])!="string"){continue;
}if(k=="qacct"){_qacct=q[k];
}else{qo+=";"+k+"="+h(q[k]);
}if(k=="media"){m=q[k];
}if(k=="event"){e=q[k];
}}_qoptions=null;
}if(_qacct.length==0){throw"";
}if(m=="webpage"&&e=="load"){if((typeof _qpixelsent!=u)&&(_qpixelsent==_qacct)){throw"";
}_qpixelsent=_qacct;
}if(typeof _qmeta!=u&&_qmeta){qm=";m="+h(_qmeta);
_qmeta=null;
}_qimg=new Image();
_qimg.alt="";
_qimg.src=(window.location.protocol=="https:"?"https://secure":"http://pixel")+".quantserve.com/pixel;r="+Math.round(Math.random()*2147483647)+";ns="+(self==top?"0":"1")+";url="+h(window.location.href)+";ref="+h(window.document.referrer)+";et="+new Date().getTime()+";a="+_qacct+qo+qm;
}catch(e){}}